import { RawFormData } from "~/interfaces/new-member";

export const formDataParser = (formData: FormData) => {
  const rawFormData: RawFormData = {
    firstName: formData.get("firstName")?.toString(),
    lastName: formData.get("lastName")?.toString(),
    tel: formData.get("tel")?.toString(),
    idCard: formData.get("idCard")?.toString(),
    address1: formData.get("address1")?.toString(),
    province: formData.get("province")?.toString(),
    amphoe: formData.get("amphoe")?.toString(),
    district: formData.get("district")?.toString(),
    zipcode: formData.get("zipcode")?.toString(),
    farmName: formData.get("farmName")?.toString(),
    farmLogo: formData.get("farmLogo")?.toString(),
    farmAddress1: formData.get("farmAddress1")?.toString(),
    farmProvince: formData.get("farmProvince")?.toString(),
    farmAmphoe: formData.get("farmAmphoe")?.toString(),
    farmDistrict: formData.get("farmDistrict")?.toString(),
    farmZipCode: formData.get("farmZipCode")?.toString(),
    farmSize1: formData.get("farmSize1")?.toString(),
    farmSize2: formData.get("farmSize2")?.toString(),
    farmSize3: formData.get("farmSize3")?.toString(),
    animalType: formData.get("animalType")?.toString(),
    animalTypeOther: formData.get("animalTypeOther")?.toString(),
    momCount: formData.get("momCount")?.toString(),
    momBread: formData.get("momBread")?.toString(),
    dadCount: formData.get("dadCount")?.toString(),
    dadBread: formData.get("dadBread")?.toString(),
    otherAnimalSize: formData.get("otherAnimalSize")?.toString(),
    children: formData.get("children")?.toString(),
    totalAnimalInFarm: formData.get("totalAnimalInFarm")?.toString(),
    farmObj1: formData.get("farmObj1")?.toString(),
    farmObj2: formData.get("farmObj2")?.toString(),
    farmObj3: formData.get("farmObj3")?.toString(),
    farmObj4: formData.get("farmObj4")?.toString(),
    farmObjOther: formData.get("farmObjOther")?.toString(),
    radioGrass: formData.get("radioGrass")?.toString(),
    radioWater: formData.get("radioWater")?.toString(),
    radioWaterOther: formData.get("radioWaterOther")?.toString(),
    radioFood: formData.get("radioFood")?.toString(),
    radioFoodOther: formData.get("radioFordOther")?.toString(),
    radioTreat: formData.get("radioTreat")?.toString(),
    radioTreatOther: formData.get("radioTreatOther")?.toString(),
    radioCertificate: formData.get("radioCertificate")?.toString(),
    radioWaterTreat: formData.get("radioWaterTreat")?.toString(),
    farmLocation: formData.get("farmLocation")?.toString(),
    idCardImage: formData.get("idCardImage")?.toString(),
    farmImage1: formData.get("farmImage1")?.toString(),
    farmImage2: formData.get("farmImage2")?.toString(),
    farmImage3: formData.get("farmImage3")?.toString(),
    framImage4: formData.get("farmImage4")?.toString(),
    radioCategory: formData.get("radioCategory")?.toString(),
    radioAccept: formData.get("radioAccept")?.toString(),
  };
};
